//! Every word the window shows, in English and Thai. The language follows Windows.

use windows::Win32::Globalization::GetUserDefaultUILanguage;

pub struct Text {
    pub thai: bool,
    pub capture: &'static str,
    pub auto_game: &'static str,
    pub screen: &'static str,
    pub hint_auto: &'static str,
    pub hint_found: &'static str,
    pub stream_to: &'static str,
    pub custom: &'static str,
    pub server: &'static str,
    pub stream_key: &'static str,
    pub key_placeholder: &'static str,
    pub show: &'static str,
    pub hide: &'static str,
    pub remember_key: &'static str,
    pub audio: &'static str,
    pub desktop: &'static str,
    pub microphone: &'static str,
    pub default_mic: &'static str,
    pub quality: &'static str,
    pub recommended: &'static str,
    pub slow_internet: &'static str,
    pub save_copy: &'static str,
    pub go_live: &'static str,
    pub record: &'static str,
    pub end_stream: &'static str,
    pub stop_recording: &'static str,
    pub ready: &'static str,
    pub connecting: &'static str,
    pub starting: &'static str,
    pub live: &'static str,
    pub recording: &'static str,
    pub reconnecting: &'static str,
    pub finishing: &'static str,
    pub upload: &'static str,
    pub dropped: &'static str,
    pub connection_good: &'static str,
    pub connection_unstable: &'static str,
    pub saved_to: &'static str,
    pub need_key: &'static str,
    pub need_server: &'static str,
    pub no_game: &'static str,
    pub window_gone: &'static str,
    pub quit_while_live: &'static str,
    pub could_not_start: &'static str,
    pub stopped_because: &'static str,
}

const EN: Text = Text {
    thai: false,
    capture: "Capture",
    auto_game: "Auto: the game you're playing",
    screen: "Entire screen",
    hint_auto: "Picks the fullscreen game when you go live",
    hint_found: "Found: ",
    stream_to: "Stream to",
    custom: "Custom",
    server: "Server",
    stream_key: "Stream key",
    key_placeholder: "Paste your stream key",
    show: "Show",
    hide: "Hide",
    remember_key: "Remember on this PC (Windows encrypts it)",
    audio: "Audio",
    desktop: "Game and desktop sound",
    microphone: "Microphone",
    default_mic: "Windows default microphone",
    quality: "Quality",
    recommended: "recommended",
    slow_internet: "slow internet",
    save_copy: "Also save a copy in Videos\\MilerCast",
    go_live: "Go live",
    record: "Record",
    end_stream: "End stream",
    stop_recording: "Stop recording",
    ready: "Ready",
    connecting: "Connecting...",
    starting: "Starting...",
    live: "LIVE",
    recording: "Recording",
    reconnecting: "Reconnecting",
    finishing: "Finishing...",
    upload: "Upload",
    dropped: "Dropped frames",
    connection_good: "Connection good",
    connection_unstable: "Connection unstable",
    saved_to: "Saved to ",
    need_key: "Paste your stream key first.",
    need_server: "Enter the server address. It starts with rtmp://",
    no_game: "No fullscreen game found. Start your game, or pick its window from the list.",
    window_gone: "That window has closed. Pick another one from the list.",
    quit_while_live: "You're live. End the stream and quit?",
    could_not_start: "Couldn't start: ",
    stopped_because: "Stopped: ",
};

const TH: Text = Text {
    thai: true,
    capture: "จับภาพจาก",
    auto_game: "อัตโนมัติ: เกมที่กำลังเล่น",
    screen: "ทั้งหน้าจอ",
    hint_auto: "จะเลือกเกมที่เปิดเต็มจอให้ตอนเริ่มไลฟ์",
    hint_found: "เจอเกม: ",
    stream_to: "ไลฟ์ไปที่",
    custom: "กำหนดเอง",
    server: "เซิร์ฟเวอร์",
    stream_key: "สตรีมคีย์",
    key_placeholder: "วางสตรีมคีย์ที่นี่",
    show: "แสดง",
    hide: "ซ่อน",
    remember_key: "จำไว้ในเครื่องนี้ (Windows เข้ารหัสให้)",
    audio: "เสียง",
    desktop: "เสียงเกมและเสียงในเครื่อง",
    microphone: "ไมโครโฟน",
    default_mic: "ไมค์หลักของ Windows",
    quality: "คุณภาพ",
    recommended: "แนะนำ",
    slow_internet: "เน็ตช้า",
    save_copy: "บันทึกสำเนาไว้ที่ Videos\\MilerCast ด้วย",
    go_live: "เริ่มไลฟ์",
    record: "อัดวิดีโอ",
    end_stream: "จบไลฟ์",
    stop_recording: "หยุดอัด",
    ready: "พร้อม",
    connecting: "กำลังเชื่อมต่อ...",
    starting: "กำลังเริ่ม...",
    live: "กำลังไลฟ์",
    recording: "กำลังอัด",
    reconnecting: "กำลังเชื่อมต่อใหม่",
    finishing: "กำลังจบ...",
    upload: "อัปโหลด",
    dropped: "เฟรมตก",
    connection_good: "การเชื่อมต่อดี",
    connection_unstable: "การเชื่อมต่อไม่เสถียร",
    saved_to: "บันทึกไว้ที่ ",
    need_key: "วางสตรีมคีย์ก่อน",
    need_server: "ใส่ที่อยู่เซิร์ฟเวอร์ที่ขึ้นต้นด้วย rtmp://",
    no_game: "ไม่เจอเกมที่เปิดเต็มจอ เปิดเกมก่อน หรือเลือกหน้าต่างเกมจากรายการ",
    window_gone: "หน้าต่างนั้นปิดไปแล้ว เลือกหน้าต่างอื่นจากรายการ",
    quit_while_live: "กำลังไลฟ์อยู่ จะจบไลฟ์และปิดโปรแกรมไหม",
    could_not_start: "เริ่มไม่ได้: ",
    stopped_because: "หยุดแล้ว: ",
};

/// Thai if Windows is set to Thai, English otherwise. MILERCAST_LANG=th or en overrides it.
pub fn current() -> &'static Text {
    const LANG_THAI: u16 = 0x1E;
    match std::env::var("MILERCAST_LANG").as_deref() {
        Ok("th") => &TH,
        Ok("en") => &EN,
        _ if unsafe { GetUserDefaultUILanguage() } & 0x3FF == LANG_THAI => &TH,
        _ => &EN,
    }
}
