//! Every word the window shows, in English and Thai. The language follows Windows.

use windows::Win32::Globalization::GetUserDefaultUILanguage;

pub struct Text {
    pub thai: bool,
    // Home
    pub capture: &'static str,
    pub auto_game: &'static str,
    pub screen: &'static str,
    pub hint_auto: &'static str,
    pub hint_found: &'static str,
    pub stream_to: &'static str,
    pub custom: &'static str,
    pub key_saved: &'static str,
    pub key_missing: &'static str,
    pub add_key: &'static str,
    pub change_key: &'static str,
    pub sound: &'static str,
    pub game: &'static str,
    pub mic: &'static str,
    pub camera: &'static str,
    pub show: &'static str,
    pub hide: &'static str,
    pub go_live: &'static str,
    pub record: &'static str,
    pub settings: &'static str,
    // Live panel
    pub connecting: &'static str,
    pub starting: &'static str,
    pub live: &'static str,
    pub recording: &'static str,
    pub reconnecting: &'static str,
    pub finishing: &'static str,
    pub upload: &'static str,
    pub dropped: &'static str,
    pub connection_good: &'static str,
    pub connection_unstable: &'static str,
    pub mic_on: &'static str,
    pub mic_off: &'static str,
    pub game_on: &'static str,
    pub game_off: &'static str,
    pub camera_on: &'static str,
    pub camera_off: &'static str,
    pub hotkeys: &'static str,
    pub end_stream: &'static str,
    pub stop_recording: &'static str,
    pub cancel: &'static str,
    // Results and problems
    pub saved_to: &'static str,
    pub stream_ended: &'static str,
    pub could_not_start: &'static str,
    pub stopped_because: &'static str,
    pub no_game: &'static str,
    pub window_gone: &'static str,
    pub need_server: &'static str,
    pub quit_while_live: &'static str,
    // Stream key dialog
    pub key_help_youtube: &'static str,
    pub key_help_twitch: &'static str,
    pub key_help_custom: &'static str,
    pub key_placeholder: &'static str,
    pub where_key: &'static str,
    pub key_note: &'static str,
    pub save: &'static str,
    // Settings
    pub settings_title: &'static str,
    pub section_stream: &'static str,
    pub custom_server: &'static str,
    pub forget_keys: &'static str,
    pub keys_forgotten: &'static str,
    pub section_audio: &'static str,
    pub microphone: &'static str,
    pub default_mic: &'static str,
    pub mic_volume: &'static str,
    pub game_volume: &'static str,
    pub section_camera: &'static str,
    pub no_camera: &'static str,
    pub mirror: &'static str,
    pub section_quality: &'static str,
    pub quality: &'static str,
    pub recommended: &'static str,
    pub slow_internet: &'static str,
    pub save_copy: &'static str,
    pub open_folder: &'static str,
    pub close: &'static str,
    pub sizes: [&'static str; 3],
    // Tray
    pub tray_show: &'static str,
    pub quit: &'static str,
}

impl Text {
    pub fn key_title(&self, platform: &str) -> String {
        if self.thai { format!("สตรีมคีย์ {platform}") } else { format!("{platform} stream key") }
    }
}

const EN: Text = Text {
    thai: false,
    capture: "Capture",
    auto_game: "Auto: the game you're playing",
    screen: "Entire screen",
    hint_auto: "Picks the fullscreen game when you go live",
    hint_found: "Found: ",
    stream_to: "Stream to",
    custom: "Custom",
    key_saved: "✓ Key saved",
    key_missing: "No key yet",
    add_key: "Add key",
    change_key: "Change key",
    sound: "Sound",
    game: "Game",
    mic: "Mic",
    camera: "Camera",
    show: "Show",
    hide: "Hide",
    go_live: "Go live",
    record: "Record",
    settings: "Settings",
    connecting: "Connecting...",
    starting: "Starting...",
    live: "LIVE",
    recording: "Recording",
    reconnecting: "Reconnecting",
    finishing: "Finishing...",
    upload: "Upload",
    dropped: "dropped",
    connection_good: "connection good",
    connection_unstable: "connection unstable",
    mic_on: "Mic on",
    mic_off: "Mic muted",
    game_on: "Game sound on",
    game_off: "Game muted",
    camera_on: "Camera on",
    camera_off: "Camera off",
    hotkeys: "Hotkeys: Ctrl+Alt+M mic · Ctrl+Alt+G game · Ctrl+Alt+C camera",
    end_stream: "End stream",
    stop_recording: "Stop recording",
    cancel: "Cancel",
    saved_to: "Saved to ",
    stream_ended: "Stream ended",
    could_not_start: "Couldn't start: ",
    stopped_because: "Stopped: ",
    no_game: "No fullscreen game found. Start your game, or pick its window under Capture.",
    window_gone: "That window has closed. Pick another one under Capture.",
    need_server: "Set your server address in Settings first. It starts with rtmp://",
    quit_while_live: "You're live. End the stream and quit?",
    key_help_youtube: "Copy it from YouTube Studio:\nGo live > Stream settings > Stream key",
    key_help_twitch: "Copy it from the Twitch dashboard:\nSettings > Stream > Primary stream key",
    key_help_custom: "Paste the stream key your server gave you.",
    key_placeholder: "Paste your stream key",
    where_key: "Where's my key?",
    key_note: "Kept on this PC, encrypted by Windows.",
    save: "Save",
    settings_title: "MilerCast settings",
    section_stream: "Stream",
    custom_server: "Custom server",
    forget_keys: "Forget saved stream keys",
    keys_forgotten: "Stream keys removed",
    section_audio: "Audio",
    microphone: "Microphone",
    default_mic: "Windows default microphone",
    mic_volume: "Mic volume",
    game_volume: "Game volume",
    section_camera: "Camera",
    no_camera: "No camera found",
    mirror: "Mirror the camera",
    section_quality: "Quality and files",
    quality: "Quality",
    recommended: "recommended",
    slow_internet: "slow internet",
    save_copy: "Also save a copy of streams",
    open_folder: "Open recordings folder",
    close: "Close",
    sizes: ["S", "M", "L"],
    tray_show: "Show MilerCast",
    quit: "Quit",
};

const TH: Text = Text {
    thai: true,
    capture: "จับภาพจาก",
    auto_game: "อัตโนมัติ: เกมที่กำลังเล่น",
    screen: "ทั้งหน้าจอ",
    hint_auto: "จะเลือกเกมที่เปิดเต็มจอให้ตอนเริ่มไลฟ์",
    hint_found: "เจอเกม: ",
    stream_to: "ไลฟ์ไปที่",
    custom: "กำหนดเอง",
    key_saved: "✓ มีคีย์แล้ว",
    key_missing: "ยังไม่มีคีย์",
    add_key: "ใส่คีย์",
    change_key: "เปลี่ยนคีย์",
    sound: "เสียง",
    game: "เกม",
    mic: "ไมค์",
    camera: "กล้อง",
    show: "แสดง",
    hide: "ซ่อน",
    go_live: "เริ่มไลฟ์",
    record: "อัดวิดีโอ",
    settings: "ตั้งค่า",
    connecting: "กำลังเชื่อมต่อ...",
    starting: "กำลังเริ่ม...",
    live: "ไลฟ์อยู่",
    recording: "กำลังอัด",
    reconnecting: "กำลังเชื่อมต่อใหม่",
    finishing: "กำลังจบ...",
    upload: "อัปโหลด",
    dropped: "เฟรมตก",
    connection_good: "การเชื่อมต่อดี",
    connection_unstable: "การเชื่อมต่อไม่เสถียร",
    mic_on: "ไมค์เปิด",
    mic_off: "ปิดไมค์อยู่",
    game_on: "เสียงเกมเปิด",
    game_off: "ปิดเสียงเกมอยู่",
    camera_on: "กล้องเปิด",
    camera_off: "กล้องปิด",
    hotkeys: "ปุ่มลัด: Ctrl+Alt+M ไมค์ · Ctrl+Alt+G เสียงเกม · Ctrl+Alt+C กล้อง",
    end_stream: "จบไลฟ์",
    stop_recording: "หยุดอัด",
    cancel: "ยกเลิก",
    saved_to: "บันทึกไว้ที่ ",
    stream_ended: "จบไลฟ์แล้ว",
    could_not_start: "เริ่มไม่ได้: ",
    stopped_because: "หยุดแล้ว: ",
    no_game: "ไม่เจอเกมที่เปิดเต็มจอ เปิดเกมก่อน หรือเลือกหน้าต่างเกมในช่องจับภาพ",
    window_gone: "หน้าต่างนั้นปิดไปแล้ว เลือกหน้าต่างอื่นในช่องจับภาพ",
    need_server: "ตั้งที่อยู่เซิร์ฟเวอร์ในหน้าตั้งค่าก่อน (ขึ้นต้นด้วย rtmp://)",
    quit_while_live: "กำลังไลฟ์อยู่ จะจบไลฟ์และปิดโปรแกรมไหม",
    key_help_youtube: "คัดลอกจาก YouTube Studio:\nถ่ายทอดสด > การตั้งค่าสตรีม > คีย์สตรีม",
    key_help_twitch: "คัดลอกจากแดชบอร์ด Twitch:\nการตั้งค่า > สตรีม > คีย์สตรีมหลัก",
    key_help_custom: "วางสตรีมคีย์ที่ได้จากเซิร์ฟเวอร์ของคุณ",
    key_placeholder: "วางสตรีมคีย์ที่นี่",
    where_key: "หาคีย์ได้ที่ไหน?",
    key_note: "เก็บไว้ในเครื่องนี้ Windows เข้ารหัสให้",
    save: "บันทึก",
    settings_title: "ตั้งค่า MilerCast",
    section_stream: "การไลฟ์",
    custom_server: "เซิร์ฟเวอร์กำหนดเอง",
    forget_keys: "ลบสตรีมคีย์ที่บันทึกไว้",
    keys_forgotten: "ลบคีย์แล้ว",
    section_audio: "เสียง",
    microphone: "ไมโครโฟน",
    default_mic: "ไมค์หลักของ Windows",
    mic_volume: "ระดับเสียงไมค์",
    game_volume: "ระดับเสียงเกม",
    section_camera: "กล้อง",
    no_camera: "ไม่พบกล้อง",
    mirror: "กลับภาพกล้องซ้ายขวา",
    section_quality: "คุณภาพและไฟล์",
    quality: "คุณภาพ",
    recommended: "แนะนำ",
    slow_internet: "เน็ตช้า",
    save_copy: "บันทึกสำเนาของไลฟ์ไว้ด้วย",
    open_folder: "เปิดโฟลเดอร์ไฟล์อัด",
    close: "ปิด",
    sizes: ["เล็ก", "กลาง", "ใหญ่"],
    tray_show: "เปิดหน้าต่าง MilerCast",
    quit: "ออก",
};

/// Thai if Windows is set to Thai, English otherwise. MILERCAST_LANG=th or en overrides it.
pub fn current() -> &'static Text {
    const LANG_THAI: u16 = 0x1E;
    match std::env::var("MILERCAST_LANG").as_deref() {
        Ok("th") => &TH,
        Ok("en") => &EN,
        _ if unsafe { GetUserDefaultUILanguage() } & 0x3FF == LANG_THAI => &TH,
        _ => &EN,
    }
}
